name: Zip and Commit

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create ZIP file
        run: |
          zip pdf2p2.zip pdf2p2.php settings.php logs.php

      - name: Commit ZIP file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pdf2p2.zip
          git commit -m "Update pdf2p2.zip on push to main" || echo "No changes to commit"
          git push
