name: Zip and Commit
permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  zip:
    if: contains(github.event.head_commit.message, 'zip-it')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Create ZIP file
        run: |
          zip pdf2p2.zip pdf2p2.php settings.php logs.php bulk.php feed.php menu.php single-import.php cpt-terms.php pdf2p2-home.php

      - name: Commit ZIP file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pdf2p2.zip
          git commit -m "Update pdf2p2.zip on push to main" || echo "No changes to commit"
          git push
