name: Update Parsedown

on:
  workflow_dispatch:           # manual trigger
  schedule:                    # weekly update (every Monday at 00:00 UTC)
    - cron: '0 0 * * 1'

jobs:
  update-parsedown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4

      - name: Install jq (to parse JSON)
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Get latest Parsedown tag
        id: get_tag
        run: |
          TAG=$(curl -s https://api.github.com/repos/erusev/parsedown/releases/latest \
            | jq -r .tag_name)
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Download release ZIP
        run: |
          curl -L \
            https://github.com/erusev/parsedown/archive/refs/tags/${{ steps.get_tag.outputs.tag }}.zip \
            -o parsedown.zip

      - name: Extract Parsedown.php
        run: |
          unzip -p parsedown.zip \
            parsedown-${{ steps.get_tag.outputs.tag }}/Parsedown.php \
            > Parsedown.php

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Parsedown.php
          if git diff --cached --quiet; then
            echo "No update needed; Parsedown.php is already up to date."
          else
            git commit -m "chore: bump Parsedown to ${{ steps.get_tag.outputs.tag }}"
            git push
          fi
